AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Copyright:
  # AutocorrectNotice: |
  #   # Copyright (c) 2019 Valencia Management Group
  #   # All rights reserved.
  Notice: '^# Copyright (\(c\) )?2[0-9]{3} .+'
  Exclude:
    - 'bin/**/*'
