AllCops:
  Include:
    - Gemfile
    - Rakefile
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 32

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false
